"""Static, zero-network labels for deterministic movie headers.

These tables are intentionally boring: downstream renderers can import them
without consulting TMDB or any other external source.
"""

from __future__ import annotations

GENRE_EN_TO_ZH: dict[str, str] = {
    "Action": "动作",
    "Adventure": "冒险",
    "Animation": "动画",
    "Comedy": "喜剧",
    "Crime": "犯罪",
    "Documentary": "纪录片",
    "Drama": "剧情",
    "Family": "家庭",
    "Fantasy": "奇幻",
    "History": "历史",
    "Horror": "恐怖",
    "Music": "音乐",
    "Mystery": "悬疑",
    "Romance": "爱情",
    "Science Fiction": "科幻",
    "TV Movie": "电视电影",
    "Thriller": "惊悚",
    "War": "战争",
    "Western": "西部",
    "Foreign": "外语",
}

LANG_CODE_TO_ZH: dict[str, str] = {
    "af": "南非荷兰语",
    "ar": "阿拉伯语",
    "az": "阿塞拜疆语",
    "bg": "保加利亚语",
    "bn": "孟加拉语",
    "ca": "加泰罗尼亚语",
    "cs": "捷克语",
    "da": "丹麦语",
    "de": "德语",
    "el": "希腊语",
    "en": "英语",
    "es": "西班牙语",
    "et": "爱沙尼亚语",
    "eu": "巴斯克语",
    "fa": "波斯语",
    "fi": "芬兰语",
    "fr": "法语",
    "ga": "爱尔兰语",
    "he": "希伯来语",
    "hi": "印地语",
    "hr": "克罗地亚语",
    "hu": "匈牙利语",
    "hy": "亚美尼亚语",
    "id": "印度尼西亚语",
    "is": "冰岛语",
    "it": "意大利语",
    "ja": "日语",
    "ka": "格鲁吉亚语",
    "km": "高棉语",
    "ko": "韩语",
    "lo": "老挝语",
    "lt": "立陶宛语",
    "lv": "拉脱维亚语",
    "mk": "北马其顿语",
    "mn": "蒙古语",
    "ms": "马来语",
    "ne": "尼泊尔语",
    "nl": "荷兰语",
    "no": "挪威语",
    "pl": "波兰语",
    "pt": "葡萄牙语",
    "ro": "罗马尼亚语",
    "ru": "俄语",
    "si": "僧伽罗语",
    "sk": "斯洛伐克语",
    "sl": "斯洛文尼亚语",
    "sr": "塞尔维亚语",
    "sv": "瑞典语",
    "sw": "斯瓦希里语",
    "ta": "泰米尔语",
    "th": "泰语",
    "tl": "他加禄语",
    "tr": "土耳其语",
    "uk": "乌克兰语",
    "ur": "乌尔都语",
    "vi": "越南语",
    "zh": "中文",
}